# Generated by Django 5.2 on 2025-04-05 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_round', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Game Session',
                'verbose_name_plural': 'Game Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('device_id', models.CharField(max_length=100)),
                ('buzzer_sound', models.CharField(default='default', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.gamesession')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['-score', 'name'],
                'unique_together': {('game_session', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BuzzEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_timestamp', models.BigIntegerField()),
                ('server_timestamp', models.BigIntegerField(default=0)),
                ('time_offset', models.IntegerField(default=0)),
                ('round_number', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzz_events', to='game.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzz_events', to='game.player')),
            ],
            options={
                'verbose_name': 'Buzz Event',
                'verbose_name_plural': 'Buzz Events',
                'ordering': ['client_timestamp'],
            },
        ),
    ]
